/**
 * Fixes missing Duration metadata in WebM files generated by browser MediaRecorder.
 * MediaRecorder produces WebM streams without duration headers, causing players to show Infinity / 0:00.
 */
export async function fixWebmDuration(webmBlob: Blob, durationMs: number): Promise<Blob> {
  if (!webmBlob || durationMs <= 0) return webmBlob;

  try {
    const buffer = await webmBlob.arrayBuffer();
    const data = new Uint8Array(buffer);

    // Find Segment Info block header (0x1549A966)
    let segmentInfoOffset = -1;
    for (let i = 0; i < data.length - 4; i++) {
      if (data[i] === 0x15 && data[i + 1] === 0x49 && data[i + 2] === 0xa9 && data[i + 3] === 0x66) {
        segmentInfoOffset = i;
        break;
      }
    }

    if (segmentInfoOffset === -1) {
      return webmBlob;
    }

    // Prepare Duration Element (ID: 0x4489, 4-byte Float representation in ms)
    const durationData = new ArrayBuffer(8);
    const view = new DataView(durationData);
    // Write 0x4489 ID (2 bytes) + Length 4 (1 byte) + IEEE 754 Float32 Duration (4 bytes)
    view.setUint16(0, 0x4489, false);
    view.setUint8(2, 4);
    view.setFloat32(3, durationMs, false);

    const patchedHeader = new Uint8Array(durationData);

    // Check if Duration (0x4489) already exists in Segment Info
    let existingDurationOffset = -1;
    for (let i = segmentInfoOffset; i < Math.min(segmentInfoOffset + 200, data.length - 2); i++) {
      if (data[i] === 0x44 && data[i + 1] === 0x89) {
        existingDurationOffset = i;
        break;
      }
    }

    if (existingDurationOffset !== -1 && existingDurationOffset + 7 <= data.length) {
      // Overwrite existing duration bytes
      const resultData = new Uint8Array(data.length);
      resultData.set(data);
      resultData[existingDurationOffset + 2] = 4; // length 4 bytes float
      const floatView = new DataView(resultData.buffer, existingDurationOffset + 3, 4);
      floatView.setFloat32(0, durationMs, false);
      return new Blob([resultData], { type: webmBlob.type || 'video/webm' });
    } else {
      // Inject duration header right after Segment Info header
      const insertAt = segmentInfoOffset + 12;
      const resultData = new Uint8Array(data.length + 7);
      resultData.set(data.subarray(0, insertAt), 0);
      resultData.set(patchedHeader.subarray(0, 7), insertAt);
      resultData.set(data.subarray(insertAt), insertAt + 7);
      return new Blob([resultData], { type: webmBlob.type || 'video/webm' });
    }
  } catch (err) {
    console.warn('Failed to fix WebM duration header:', err);
    return webmBlob;
  }
}
